#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
try:
    import builtins as builtin
except ImportError:
    import __builtin__ as builtin
from os.path import getmtime, exists
import time
import types
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import *
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers

##################################################
## MODULE CONSTANTS
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '2.4.4'
__CHEETAH_versionTuple__ = (2, 4, 4, 'development', 0)
__CHEETAH_genTime__ = 1506526473.82601
__CHEETAH_genTimestamp__ = 'Wed Sep 27 12:34:33 2017'
__CHEETAH_src__ = '../m/db_127.tmpl'
__CHEETAH_srcLastModified__ = 'Wed Sep 27 11:52:05 2017'
__CHEETAH_docstring__ = 'Autogenerated by Cheetah: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class db_127(Template):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        super(db_127, self).__init__(*args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def respond(self, trans=None):



        ## CHEETAH: main method generated for this template
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write(u''';
; BIND reverse data file for local loopback interface
;
$TTL\t604800
@\tIN\tSOA\t''')
        write(_filter( os.popen("hostname").read().strip()))
        write(u'''.''')
        _v = VFFSL(SL,"dns.domain",True) # u'${dns.domain}' on line 5, col 53
        if _v is not None: write(_filter(_v, rawExpr=u'${dns.domain}')) # from line 5, col 53.
        write(u'''. root.''')
        _v = VFFSL(SL,"dns.domain",True) # u'${dns.domain}' on line 5, col 73
        if _v is not None: write(_filter(_v, rawExpr=u'${dns.domain}')) # from line 5, col 73.
        write(u'''. (
\t\t\t      1\t\t; Serial
\t\t\t 604800\t\t; Refresh
\t\t\t  86400\t\t; Retry
\t\t\t2419200\t\t; Expire
\t\t\t 604800 )\t; Negative Cache TTL
;
\tIN\tNS\t''')
        write(_filter( os.popen("hostname").read().strip()))
        write(u'''.
1\tIN\tPTR\trouter.''')
        _v = VFFSL(SL,"dns.domain",True) # u'${dns.domain}' on line 13, col 17
        if _v is not None: write(_filter(_v, rawExpr=u'${dns.domain}')) # from line 13, col 17.
        write(u'''.
50\tIN\tPTR\tvendas.''')
        _v = VFFSL(SL,"dns.domain",True) # u'${dns.domain}' on line 14, col 18
        if _v is not None: write(_filter(_v, rawExpr=u'${dns.domain}')) # from line 14, col 18.
        write(u'''.
40\tIN\tPTR\t''')
        write(_filter( os.popen("hostname").read().strip()))
        write(u'''.''')
        _v = VFFSL(SL,"dns.domain",True) # u'${dns.domain}' on line 15, col 54
        if _v is not None: write(_filter(_v, rawExpr=u'${dns.domain}')) # from line 15, col 54.
        write(u'''.

''')
        for x in range(0, len(VFFSL(SL,"machines",True))): # generated from line 17, col 1
            _v = VFN(VFFSL(SL,"machines",True)[x],"values",False)()[0].split('.')[3] # u"${machines[x].values()[0].split('.')[3]}" on line 18, col 1
            if _v is not None: write(_filter(_v, rawExpr=u"${machines[x].values()[0].split('.')[3]}")) # from line 18, col 1.
            write(u'''\tIN\tPTR\t''')
            _v = VFN(VFFSL(SL,"machines",True)[x],"keys",False)()[0] # u'${machines[x].keys()[0]}' on line 18, col 49
            if _v is not None: write(_filter(_v, rawExpr=u'${machines[x].keys()[0]}')) # from line 18, col 49.
            write(u'''.''')
            _v = VFFSL(SL,"dns.domain",True) # u'${dns.domain}' on line 18, col 74
            if _v is not None: write(_filter(_v, rawExpr=u'${dns.domain}')) # from line 18, col 74.
            write(u'''.
''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_db_127= 'respond'

## END CLASS DEFINITION

if not hasattr(db_127, '_initCheetahAttributes'):
    templateAPIClass = getattr(db_127, '_CHEETAH_templateClass', Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(db_127)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=db_127()).run()


